### PR TITLE
Add new Incredibles images to Pixar in a Box content

### PR DESCRIPTION
**Pull request by idreyn**
_See [LP-3444](https://khanacademy.atlassian.net/secure/RapidBoard.jspa?rapidView=40&modal=detail&selectedIssue=LP-3444) for more context._

This PR does the following:

- Adds some new images to the `/images/pixar` directory for some upcoming PiaB content
- Updates `all-images.js`

Test plan:

- Run `python -m SimpleHTTPServer 1313`
- Visit http://localhost:1313/demos/simple/
- Enter the following into the PJS editor: `image(getImage("pixar/Incredibles_a_fill"), 0, 0, 300, 125);`
- Observe that one the new Pixar in a Box images is rendered in the output

Here's one of the new images working in the PJS editor:

screenshot of the new image in live-editor

### CODE REVIEW

**Comment by JettBurns14** [comment]
Oh wow, an update! 👏 

You might already know, but the Node.js version (0.12) in `.travis.yml` is too old for certain checks to pass; [it needs to be 4.x or greater](https://stackoverflow.com/questions/22603078/syntaxerror-use-of-const-in-strict-mode).

Are you planning to fix this?

**Comment by kevinbarabash** [comment]
Thanks for updating `node`.

**Comment by kevinbarabash** [comment]
It's too bad about our tests being so flakey. 😞

**Comment by JettBurns14** [comment]
Cool!

> It's too bad about our tests being so flakey

Yeah... About time for some updates don’t ya think? I had been planning on contributing and fixing bugs as a summer project, maybe I could help out with that? 😄

**Comment by kevinbarabash** [comment]
@JettBurns14 sorry to be the bearer of bad news but we don't have any other changes planned at the current time.

**Pull request merged**
