### PR TITLE
Programable avatars support (ver. 0.1)

### PR DESCRIPTION
**Pull request by albertochiwas**
Avatar ProcessingJS object to animate an articulated SVG avatar (PShape compound object)

### CODE REVIEW

**Comment by albertochiwas** [comment]
See [Subproject Wiki](https://github.com/mLearningLab/live-editor/wiki) for more details.

**Comment by kevinb7** [comment]
@albertochiwas thanks for the pull request.  I'm going to try it out this weekend.  I think we'd like to provide a way for people to add APIs for different libraries more easily so that the source files don't need to be modified each time a person wants to add a library.

**Comment by kevinb7** [comment]
I finally had some time to check it out.  Really cool.  How much work is it to create new Avatars?

**Comment by kevinb7** [comment]
screen shot 2015-08-19 at 9 48 58 pm

Did you create the artwork for the avatars?

**Comment by albertochiwas** [comment]
Hi Kevin,

Not much. You only have to add some annotations to the SVG avatar image and
that's it. We can try a test. We can try if you will with a Khan Academy
avatar, like
https://github.com/Khan/live-editor/blob/master/build/images/avatars/svg/robot_male_2.svg

Unfortunately, we need a full body image, if you send me one full-body
avatar design I will show you how to "articulate" its SVG image.

Let's try it... by the way we have a demo working at:

http://podcast.itch.edu.mx/live-editor/

We want to add some additional functions and attributes.. like angular
constraints for each avatar body joint, so very soon we can show this new
version

Thank you for your interest and time, and we want to improve a little more
this "idea" and someday get ready to provide some programming lessons with
them (challenges).

Best regards

Alberto




2015-08-19 21:48 GMT-06:00 Kevin Barabash <notifications@github.com>:

> I finally had some time to check it out. Really cool. How much work is it
> to create new Avatars?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/pull/377#issuecomment-132875997>.
>



-- 
Saludos Cordiales,

Alberto Pacheco
Laboratorio M-Learning
DEPI, IT Chihuahua
<http://mx.televisioneducativa.gob.mx/courses/TecNM.MX/ACF-0903-1/2015_T2/about>

**Comment by MikaalSky** [comment]
Is there a possibility of pushTwords() for linearish movement?

**Comment by albertochiwas** [comment]
Hi @MikaalSky could you please share us a link and explain us a little more about pushTwords()? Thank you

**Comment by MikaalSky** [comment]
There's no links for this, but a function where you could go...
pushTwords(part,x,y,force(amount to move each time)

**Comment by albertochiwas** [comment]
Thanks @MikaalSky It's part of ProcessingJS? I will search it I think at the source code and try to apply it, it sounds interesting like a Game Physics utility

**Comment by kevinbarabash** [comment]
@albertochiwas I'm going close this pull request because we want to have a general way of importing libraries.  Please see https://github.com/Khan/live-editor/issues/385 for the current thinking around adding module support to live-editor.

**Pull request closed without merging**
