### PR TITLE
Fix for issue #466

### PR DESCRIPTION
**Pull request by alexristich**
Includes a fix for the issue with the image-picker as per issue #466.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
I checked out the code and gave it a try.  Instead of hiding the small version of the tooltip on `mouseleave`, it be better to update it.  Updating the click handler like so should do the trick:
```
.on("click", ".image", function() {
                $(this).parents(".mediapicker").find(".active").removeClass("active");
                $(this).addClass("active");
                var path = $(this).attr("data-path");
                self.updateText(path);
                self.updateTooltip(`"${path}"`);
            })
```

**Comment by kevinbarabash** [comment]
Also, you should include the build files with the changes.

**Comment by alexristich** [comment]
Ah! I had tried that first but kept running into the problem where the `data-path` wasn't being passed properly, and couldn't figure out why that was happening. My solution here was less than ideal. Thanks for the tip on this. I'll submit another PR right now with this suggestion along with the relevant build file.

**Comment by kevinbarabash** [comment]
Thanks.  Also, no need to create a new PR.  In this case you could've made the changes on your branch and committed them using `--amend` and then did a force push to github.

**Comment by alexristich** [comment]
Good to know! I deleted the commit and was a bit surprised to see that it also closed the PR automatically, though in retrospect the behavior makes sense. In any case, your tidbits of advice are greatly appreciated.

**Pull request closed without merging**
