### PR TITLE
Removed incorrect var behavior on PJS callbacks

### PR DESCRIPTION
**Pull request by Potato42**
I have not tested this and don't know if I've gotten everything, but hopefully this will be enough.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
@Potato42 cool.  I think that's the right track.  To test this you could write a test in ast_transform_tests.js to check what the transformed code looks like.  Why did you end up closing this?

**Comment by Potato42** [comment]
Because I wasn't entirely sure how to update the build folder and the other things you are supposed to do before submitting a pull request.  But yeah, that line 127 in js/output/pjs/pjs-ast-transforms.js is probably the only thing causing this bug.

**Comment by Gigabyte-Giant** [comment]
Have you seen the steps in the README?

https://github.com/Khan/live-editor#building

**Comment by Potato42** [comment]
I know, but I'm on Windows, and `npm install` tries to do `rm -rf node_modules/gulp-handlebars/node_modules/handlebars`.  I deleted the folder myself and continued to bower (which appeared to work), but gulp never finished (It got to `Finished 'default' after 96 µs`, then stopped).  
When it came to doing a basic test, despite the fact I deleted the handlebars folder myself, I got the `this.merge` issue described in the README.  I have 0 experience with node and the like (I installed them today) and really don't know what to do.  

It would just be easier if someone else deleted this one line and submitted a new pull request.

**Comment by Gigabyte-Giant** [comment]
Gulp is set to watch for changes after it finishes the default task.

Just keep gulp running, and make your changes; whenever you save a file, gulp will re-build the appropriate file(s).

**Comment by Potato42** [comment]
Ah, got it.  I still have the `this.merge` issue.  Deleting that folder and re-running everything doesn't seem to fix it.

**Comment by Gigabyte-Giant** [comment]
...just went and made this change myself, and it **doesn't actually fix the issue** that Bob Lyon reported.

I'm afraid I can't provide much more help about the `this.merge` issue, perhaps you should try asking in the [Gitter room for this repository](https://gitter.im/Khan/live-editor).

**Comment by Potato42** [comment]
Whoops, yeah.  I'm dumb.  That was in the "Identifier" node type.  The thing right below it (in "VariableDeclaration") on line 151 is (hopefully this time) the issue.
Also, btw, you will want to change the thing on line 77 in ast_transform_tests.js to reflect the change.

**Comment by kevinbarabash** [comment]
@Potato42 I'd like to make the install more windows friendly so this is good feedback.

**Pull request closed without merging**
