### PR TITLE
Toggle autosuggest via keyboard shortcut

### PR DESCRIPTION
**Pull request by Gigabyte-Giant**
Similar to what was suggested by @pamelafox on the https://github.com/Khan/live-editor/issues/311 thread.

The keyboard shortcut is `Ctrl+Alt+A`/`Command+Option+A`.
*The keyboard shortcut is not added to the editor unless `autosuggestToggle=yes` is found in the URL*

I have yet to implement a menu, instead, this is a simple toggle.

A couple notes:
 • I did not include the new[er] files from the /build directory
 • I did **not** write any tests for this, as I didn't really feel it was necessary for a change like this (however, I can write one if needed).

Todo List:
 - [x] Figure out why AutoSuggest isn't using the value loaded from localStorage.

**Update**:
I won't be implementing a settings menu in this PR, as I have yet to figure out *how* I'm going to implement one. I will continue to work on a settings menu, and open another PR at a later time.
This PR is ready to be merged.

### CODE REVIEW

**Comment by Gigabyte-Giant** [comment]
As it would appear, the localstorage data isn't being used upon initialization of the TooltipEngine. Will take a look at that.

**Comment by JavascriptFTW** [comment]
Why are you using the Boolean constructor? The enabled property should never be anything but a Boolean with the way that you use it, plus if you just want to convert a value to its Boolean equivalent you can just put double exclamation points in front of it (!!variableName) instead since using the constructors for types such as Number and Boolean is generally considered bad practice.

**Comment by kevinb7** [comment]
I didn't even know there was a ```Boolean``` constructor.  In this case it is not being called as a constructor.  If you call ```new Boolean()``` jshint should pick it up as an error and fail the build.  I tried it on jshint.com.  I am more familiar with the ```!!```, but ```Boolean(value)``` seems less cryptic.

@Gigabyte-Giant It doesn't seem like we have any tests for error buddy popping up.  We test the messages but not the UI.  We probably should add some at some point just as a sanity check, but for this it's probably not necessary.

**Comment by kevinb7** [comment]
@Gigabyte-Giant Are you planning to add a menu to this pull request?

**Comment by Gigabyte-Giant** [comment]
@kevinb7 Yes, I do intend on trying to implement some form of menu to this PR. However, before I do that, I want to figure out why `TooltipEngine` isn't loading the `autosuggest-enabled` (shortened to `autosuggest`) value from localStorage upon init...

@JavascriptFTW I used that for testing purposes, just so I knew exactly what was going on. I removed it/them in https://github.com/Gigabyte-Giant/live-editor/commit/a43ec180b91256eb7b20eb530e8b5d4a589c7901.

Also, as a side note: All of this code should conform with KA's JS style guide, if it doesn't, please let me know so I can fix it.

**Comment by Gigabyte-Giant** [comment]
Just a heads up, the Travis CI build is likely to have issues, as the tooltip tests fail for some reason...

**Comment by Gigabyte-Giant** [comment]
The editor now loads, and recognizes the value loaded from `localStorage`. Everything should build fine as well.

Will now look into implementing a settings menu @kevinb7.

**Comment by Gigabyte-Giant** [comment]
Ref: https://github.com/ajaxorg/ace/pull/1338

**Comment by Gigabyte-Giant** [comment]
@kevinb7 I won't be implementing a settings menu in this PR, as I have yet to figure out how I'm going to implement one. I will continue to work on a settings menu, and open another PR at a later time.

**Comment by kevinb7** [comment]
@Gigabyte-Giant That's cool.  Could you hide these changes behind a URL param?  That way we can merge your changes without affecting production.

**Comment by MikaalSky** [comment]
(Like ?supersecretsettings plz)

**Comment by Gigabyte-Giant** [comment]
@kevinb7 Sure, I'll see what I can do.

**Comment by kevinb7** [comment]
@Gigabyte-Giant what I meant was to hide the toggle behaviour behind a flag.  That way people can try toggling error buddy interactively.  In your most recent diff people would have to reload the browser to toggle error buddy.  I'm curious to see what happens if turn him off, write some bad code, and then turn him on.  Does he pop up in that case?

**Comment by Gigabyte-Giant** [comment]
@kevinb7 I don't have a toggle for the Error Buddy, just a toggle for the autosuggestions.

I'll hide the keyboard shortcut behind my URL param, that way you could do something like `?experimental=yes` or something, and get access to this toggle.

Should I add a toggle for the Error Buddy? I know some users have asked for that, but I wasn't headed in that direction with this PR.

**Comment by kevinb7** [comment]
@Gigabyte-Giant my bad... sorry, yes, auto suggestions.  ```experimental``` is a bit general, maybe ```enableAutosuggestToggle```.  Eventually we'll replace that with ```enableSettingsMenu```.

**Comment by Gigabyte-Giant** [comment]
@kevinb7 Done! I changed the parameter to `autosuggestToggle`. If you add `autosuggestToggle=yes` to the end of the URL, the keystroke will be added to the editor. :-)

**Comment by kevinb7** [comment]
Sorry for all of this back-and-forth.  I just noticed that ```tooltipEngine.enabled``` is now a string.  This should probably be a boolean like it was before.  Why the change?

**Comment by Gigabyte-Giant** [comment]
No worries, I'm perfectly fine with that @kevinb7...

The localStorage value is a string, for whatever reason, and treating it as causes problems. Give me a few minutes and I'll see if I can figure out a way around those problems.

**Comment by Gigabyte-Giant** [comment]
Alright @kevinb7, it's a boolean once again. I figured out a simple simple workaround. Everything should work just fine! :)

**Comment by Gigabyte-Giant** [comment]
...odd, I have no clue why the Travis CI build fails, it all works fine on my local machine.

**Comment by kevinb7** [comment]
I don't think it's your code.  I think it's travis-ci.  Those tests have been finicky... I thought I had the issue nailed down, but apparently not.  I checked out your code and ran the tests and they pass.  Could you include your build files too?  Then we'll merge this.

I was talking with @pamelafox and she mentioned that not all browsers support localStorage and that even if it does, there's a chance that the quota may have been reached.  I had a look at http://caniuse.com/#search=localstorage and it looks like we're covered.  The quota issue is a real thing that we should deal with before take away the url parameter.  It sounds like there's some libraries out there which might smooth over the raw API so I'd like to investigate what would be a good choice.

@pamelafox's slide deck with best practices: http://localstorage-use-not-abuse.appspot.com/

**Comment by MikaalSky** [comment]
There could be an addition to the api to set a users settings menu options with a post or put request. The realtime live editor stuff should be in the session js, tho.

**Comment by Gigabyte-Giant** [comment]
@kevinb7 I'll include those, yes.

I'll take a look at @pamelafox's slides, and will take them into account! :)

**Comment by kevinb7** [comment]
There's definite something funking going on with your repo.  When I checked it out last night ```git submodule update``` didn't work properly.  I thought it was just an issue on my end, but I can see it's not because the build files are missing many of the dependencies.  There's also some other issues with how we're building stuff in general, see: https://github.com/Khan/live-editor/issues/322 and https://github.com/Khan/live-editor/issues/326.

So... while I figure out how to make our build pipeline better, please revert the last commit and I'll merge.

**Comment by Gigabyte-Giant** [comment]
Should be reverted @kevinb7.
I'm unsure what's wrong with my repo, `git submodule update` works fine for me.

**Comment by Gigabyte-Giant** [comment]
...wait, everything is screwed up now. Hold on...

**Comment by kevinb7** [comment]
@Gigabyte-Giant When I ran ```git submodule update``` it completes without an error, but it didn't actually grab any of the submodules.  I also tried ```git submodule sync```, no effect.  I need to investigate further what's going on here.   Have a look at the folders in /external.  I'm guess a number of them are empty and that's why many of dependencies are missing from the build file.

**Comment by Gigabyte-Giant** [comment]
@kevinb7 Yes, pretty much all of those are empty... I have tried pushing the `build/` dir again.

**Comment by Gigabyte-Giant** [comment]
...going to re-clone all the files in the current live-editor repo, and add my changes again.

**Comment by kevinb7** [comment]
Uh-oh... it might be easier to start a new pull request with just your changes to ```js/```.  Also, in the future create branches for your pull requests, it tends to make things easier.

**Comment by Gigabyte-Giant** [comment]
Am going to do that @kevinb7. Apologies about the inconvenience.

**Comment by kevinb7** [comment]
No worries, take your time.  Have a look at "git reset [<mode>] [<commit>]" in http://git-scm.com/docs/git-reset.  You should be able to do "git reset --hard e3cd4e3de1f0ea5645d34f8b07c3e1013434c08a" which will get rid of commits since "Small changes".  Then you can force push those changes to github, just make sure that it had the intended effect before doing so.  "git push origin master --force"

**Comment by Gigabyte-Giant** [comment]
It should be fine now. Now I'm just watching the Travis CI build. Once again, I do apologize for the inconvenience(s); they weren't very professional.

**Comment by MikaalSky** [comment]
_pats @Gigabyte-Giant on the back_

**Comment by kevinb7** [comment]
Don't sweat it.  I've messed all sorts of stuff with git.

**Comment by MikaalSky** [comment]
So, about how long until this is pushed to Khan? An hour, day, week..?

**Comment by pamelafox** [comment]
Our deploy cycle depends on when Kevin or I make the next deploy. It's
typically within a day to a week. Each deploy takes a fair amount of time
to do, so we typically batch a few changes up and do them.

**Comment by MikaalSky** [comment]
Got it, thanks Pamela.

**Comment by kevinb7** [comment]
@Gigabyte-Giant try running the following command to grab all of the submodules:
```
git submodule update --init --recursive
```
I did a fresh checkout/clone today and had the same problem again and this did the trick.

**Comment by kevinb7** [comment]
I've update the README to reflect this as well.

**Pull request merged**
