### PR TITLE
change number scrubber arrows to svg

### PR DESCRIPTION
**Pull request by shockry**
Fix for issue #338

### CODE REVIEW

**Comment by MatthiasSaihttam** [comment]
I went ahead and tried this out; it seems to work perfectly.

**Comment by kevinbarabash** [comment]
@shockry thanks for the pull request.  Could you post a screenshot of the change in action?

**Comment by shockry** [comment]
The cursor changes normally to pointer and resize when hovering over different parts of the scrubber, my screen recorder just didn't catch that

ren7enxhfl

**Comment by kevinbarabash** [comment]
LGTM.

**Comment by darrylyeo** [comment]
This resolves issue #544.

**Pull request merged**
