### PR TITLE
Javascript's parseInt and new Images

### PR DESCRIPTION
**Pull request by MatthiasSaihttam**
This includes the changes suggested in #584, adding the hidden avatars to the image picker, making that PR obsolete.
It also changes `parseInt` to use native Javascript instead of Processing's code, fixing #551. 

Edit: This appears to be including changes from my last PR, that have already been merged. It's only the last three commits that need to be included, but in theory it wouldn't hurt to re-do the changes already made.

### CODE REVIEW

**Comment by kevinbarabash** [comment]
This is very weird.  It looks like github is confused.  Could you create separate pull requests for the images additions and the `parseInt` change?

**Comment by MatthiasSaihttam** [comment]
Sure, it might take me a while, but I'll see what I can do.

**Comment by Gigabyte-Giant** [comment]
Just a quick word of advice @MatthiasSaihttam:

Whenever you get ready to fix a bug, or add a feature, **[create a new branch](https://git-scm.com/book/en/v2/Git-Branching-Basic-Branching-and-Merging)** in your fork of the live-editor repository.
Doing so, makes it much easier to submit pull requests, as you'll just request to merge `MatthiasSaihttam:yourFeature` into `Khan:master`.

**Comment by MatthiasSaihttam** [comment]
Yea, I'm going to start doing that. I figured it would make things more complicated having to worry about different branches, but it's probably worth it. Thanks for the advice.

**Comment by kevinbarabash** [comment]
Doing PRs from branches adds a little overhead, but they're super helpful if you want to update your master to to match `khan/live-editor`'s `master`.

**Comment by Gigabyte-Giant** [comment]
Exactly what @kevinbarabash said. It takes a little bit more effort, but, in my opinion, it's worth it in the long run.

They can definitely also help prevent problems like was experienced with this PR (multiple commits that've already been merged).

**Pull request closed without merging**
