### PR TITLE
Update 'ace-builds' to latest version

### PR DESCRIPTION
**Pull request by Gigabyte-Giant**
This PR was opened to keep track of things that get-fixed/break whenever Ace gets updated.

#### live-editor bugs fixed by this
 * https://github.com/Khan/live-editor/issues/269
 * https://github.com/Khan/live-editor/issues/408

#### Everything else is being tracked on this Trello board: https://trello.com/b/eKPYPTjm

I'll continue testing the live-editor with the latest version of Ace to see what all I'll need to fix.

### CODE REVIEW

**Comment by pamelafox** [comment]
Oh, you submitted a PR already, great! Please continue fixing/testing, and let us know when the PR is updated.

**Comment by Gigabyte-Giant** [comment]
Will do @pamelafox!

**Comment by pamelafox** [comment]
What are your thoughts on timeline for this PR? Hour of Code is a week from now, so if we are making any live-editor changes (like this one which may have unexpected results), we need to get them deployed in the next few days.

**Comment by Gigabyte-Giant** [comment]
If I get some time this week, I'll try and work on this some more...

I've got a lot of things on my to-do list, plus I'm working on trying to find a job. Due to those circumstances, I don't think I'll be able to get this ready for Hour of Code, unfortunately.

**Comment by pamelafox** [comment]
Okay, thanks for the update! I'll assume we won't deploy this unless I or another KAer finds time early this week.

**Comment by Gigabyte-Giant** [comment]
I sort-of have a plan in my head of what I need to do to get this finished, so I *might* get it ready in time, but that's a really big "*might*"...

I'll keep you posted.

**Comment by pamelafox** [comment]
We've decided to disable autosuggest entirely for now, since it will likely be more confusing than it is helpful for the many new programmers coming in next week. We'd also like to experimental with having subsets of keywords in the autosuggest for the early challenges.

**Comment by Gigabyte-Giant** [comment]
Interesting decision... So, by disabling autosuggest, you're also disabling autocomplete, correct?

**Comment by pamelafox** [comment]
Yes, that's what I mean (it's called autosuggest in the code from what I can tell, we seem to call it both things in the issue trackers).

**Comment by Gigabyte-Giant** [comment]
You're right. In the live-editor code, it's referred to as "autosuggest".

I referred to the two things separately because suggestions and completions are very different in my head, but that's just me.

**Comment by Gigabyte-Giant** [comment]
I'm going to go ahead and close this, as I can't afford to dedicate time to volunteer projects like these anymore.

Sorry I didn't get this ready for Hour of Code...

**Comment by kevinbarabash** [comment]
No worries.  Thanks for trying.  At least we have a better idea of what the issues are.

**Comment by sedge** [comment]
Is there still interest in this? I'd be happy to give it a go.

**Comment by kevinbarabash** [comment]
@sedge we'd love to have this.  Any help we can get on this would be greatly appreciated.

**Comment by sedge** [comment]
@Gigabyte-Giant made some good progress on this. I'll pick up where he left off.

**Pull request closed without merging**
