### PR TITLE
fix scrubbing in non pjs environments

### PR DESCRIPTION
**Pull request by kevinb7**
Don't skip linting in non pjs environments.

### CODE REVIEW

**Comment by kevinb7** [comment]
linting in the webpage environment generates slowparseResults which are then used in the runCode step so skipping linting won't work in that environment without some more work.

**Comment by kevinb7** [comment]
Addresses issue https://github.com/Khan/live-editor/issues/256.

**Comment by pamelafox** [comment]
We're not particularly well set up to be able to test this, ay? 
Can you add this comment to the code above the if?
"linting in the webpage environment generates slowparseResults which are then used in the runCode step so skipping linting won't work in that environment without some more work."

**Comment by kevinb7** [comment]
With some work we could test things like that.  I've done lots of stuff with simulating mouse events and checking pixels and the DOM.  As a start though I'd like to automate the tests that we have using travis-ci.  Once that's in place I think it makes more sense to tackle writing some functional tests.

**Comment by kevinb7** [comment]
@pamelafox is there some part of the pipeline that is already running the existing tests automatically?

**Comment by pamelafox** [comment]
Good Q, answer is no, not currently. Travis-CI would make sense for this repo, I think it's free for OSS projects? 
Internally we use mocha/chai/sinon plus phantomJS, with jenkins automation.

**Pull request merged**
