### PR TITLE
Fixes to tooltip UI #457

### PR DESCRIPTION
**Pull request by alexristich**
Fixes for tooltip issues (issue #457). Includes:
1) Fix for tooltip flicker when moving the cursor with the mouse
2) Fix for tooltip not disappearing properly when moving from a function to a comment
3) Fix for autosuggest incorrectly triggering within comment

### CODE REVIEW

**Comment by kevinbarabash** [comment]
You should be making changes to the files in js/ and then build the files using `gulp`.  I'll checkout the revision to try out the new behavior later this week when I have a bit more time.

**Comment by alexristich** [comment]
Thanks for the heads up! I'll do that from now on. I still have a few more things to fix wrt the tooltips/popups and should hopefully have some time later this week or this weekend to spend on this.

**Comment by alexristich** [comment]
I noticed one of my changes here introduced a new bug and ended up not being necessary. The bug was that the number-scrubber wasn't showing up properly for numbers within a function's parameters. I've just made another commit that reverts this fix, so it should be working properly again in this pending PR.

**Comment by kevinbarabash** [comment]
I finally got around to checking out the code.  It definitely fixes some of the issues, but not all of them.  I have verified that the flickering is gone and the issue with the tooltip remaining up when the cursor is in a comment is gone.  The regex is still not quite right, but I feel like creating a regex that handles all situations is probably not possible.  Doing so will probably require inspecting the AST, but this should not be part of another diff.

Could you squash you commits and rebase?  It seems like there's some changes in the build files that are unrelated to the changes in the source files.

**Comment by alexristich** [comment]
Duly noted. My first commit to the /build directory really muddled things up. Let me tidy things up hopefully this evening so it'll be ready to go.

On the regex, I definitely cheated somewhat - it indeed is very tricky to come up with something that covers all cases, and perhaps not a huge priority at this time. This patch will help from the user's perspective, but still leaves something to be desired.

In any case, will let you know when this PR should be ready to go.

**Comment by alexristich** [comment]
Kevin, I've squashed the commit - took me a bit to figure it out, though hopefully I did it correctly. If not please let me know! Also, is there a better way to merge from the Khan/master branch, or is how I've done it here correct?

Regarding the flicker, the issue is in the `ace.js` file, which is from the `ace_builds` repo as you probably already know. The change required to fix the flicker needs to be made there, as the only way to fix it here is to make the change in the `/build` directory, which will just get overwritten on the next build.

I found making the following change fixed the flicker, and as far as I could tell it didn't cause any other undesirable side-effects:

```
setTimeout(function(){
            if (shiftPressed) {
                editor.selection.selectToPosition(pos);
            }
            else if (!this.$clickSelection) {
                editor.selection.moveToPosition(pos);
            }
            this.select();
        }.bind(this), 0);
```

to:
```if (shiftPressed) {
            editor.selection.selectToPosition(pos);
        }
        else if (!this.$clickSelection) {
            editor.selection.moveToPosition(pos);
        }
        this.select();
```

**Comment by kevinbarabash** [comment]
> Regarding the flicker, the issue is in the ace.js file, which is from the ace_builds repo as you probably already know. The change required to fix the flicker needs to be made there, as the only way to fix it here is to make the change in the /build directory, which will just get overwritten on the next build.

I didn't realize that this required a change to ace.  We should try to make this change upstream and then update ace.

**Comment by kevinbarabash** [comment]
Let's focus on getting the fixes for issues 2 and 3 merged in.  There are still a couple of things wrong with the pull request: it shouldn't include that first merge commit and the second commit should include the build files.  It's probably easiest to create a new pull request using a new branch similar to what you did with https://github.com/Khan/live-editor/pull/483.

**Comment by alexristich** [comment]
Sounds good - I'll submit a new PR tonight for this one.

**Pull request closed without merging**
