### PR TITLE
Add Duskpin

### PR DESCRIPTION
**Pull request by jcstudios**

### CODE REVIEW

**Comment by MikaalSky** [comment]
Why just duskpin

**Comment by jcstudios** [comment]
Because it's my favorite.

**Comment by kevinbarabash** [comment]
@jcstudios sorry for taking so long.  Could you change this to be a vertically formatted array so that it's easier to see additions in the future.  Also, could you run `gulp build` and include the build files?

**Comment by kevinbarabash** [comment]
whoops... didn't mean to close this.

**Comment by MatthiasSaihttam** [comment]
I was think about this, and wondered if we should be adding the hidden avatars. Previously (I believe) avatars haven't been (formally) added to the live editor until after they've added to the site and have been made obtainable. If we do go ahead and add Duskpin, shouldn't we also add the other "hidden" avatars (Primosaur and Starky)? If you'd like them to be added I'd be willing to make the code changes.

**Comment by kevinbarabash** [comment]
@MatthiasSaihttam we can add those other avatars as well.

**Comment by kevinbarabash** [comment]
@jcstudios friendly ping.

**Comment by Gigabyte-Giant** [comment]
This should be closed, as-per https://github.com/Khan/live-editor/commit/e20cfbbea7097d595391281c935549c3c215d3f3.

**Comment by rileyjshaw** [comment]
Oops, I didn't see this - sorry for duplicating your work @jcstudios!

Duskpin (and friends) will be on the site soon 😄

**Pull request closed without merging**
