### PR TITLE
Hardcoded parameter count for getImage

### PR DESCRIPTION
**Pull request by Gigabyte-Giant**
While unable to replicate the issue, this is a minor change to [attempt to] fix https://github.com/Khan/live-editor/issues/339.

I've included all the rebuilt files in this PR.

### CODE REVIEW

**Comment by kevinb7** [comment]
Cool.  Why the file mode change in live-editor.audio.js?

**Comment by Gigabyte-Giant** [comment]
...not sure, I didn't notice that. I know something in the gulp build failed (something with `getSound`, which I didn't touch); would that have anything to do with it?

**Comment by kevinb7** [comment]
Can you post the failure?

**Comment by Gigabyte-Giant** [comment]
Sure thing!

image

**Comment by MikaalSky** [comment]
Don't really know how the build system works really, but does this have anything to do with it?
https://github.com/Khan/live-editor/issues/352

**Comment by Gigabyte-Giant** [comment]
I don't believe it does @MikaalSky; that issue did show itself when I was doing an initial build, before making any changes, but hasn't done it since.

You'll notice, the gulp build didn't exit; it finished. The only thing that went "wrong", was the two tests that ran out of time.

**Comment by kevinb7** [comment]
Those errors are "okay".  They only show up when running the tests on the console.  It has something to do phantomjs.  I'll try and get those fixed this weekend, don't worry about them.  @MikaalSky that's actually a different issue which I'm also going to try and fix this weekend.  @Gigabyte-Giant I think that changing the permissions to 644 is the right thing to do so I'm going to merge this.

**Comment by kevinb7** [comment]
@Gigabyte-Giant thanks for the pull request.

**Comment by Gigabyte-Giant** [comment]
Always happy to help!

Will be trying to get my head into the live-editor more and more over the next few days/weeks/months; as it's all really interesting work.

:)

**Comment by kevinb7** [comment]
Glad to hear that.  I find it really interesting too!

**Pull request merged**
