### PR TITLE
OhNoes-Happy/Hmm Edits

### PR DESCRIPTION
**Pull request by MikaalSky**
ohnoes-happy.png and ohnoes-hmm.png were changed.

### CODE REVIEW

**Comment by kevinb7** [comment]
Thank you for the pull request.  There were some changes we were looking to make based on feedback.  I'm going to talk with @pamelafox about this next week.

**Comment by kevinb7** [comment]
@MikaalSky I just finally clued into the fact you have two github accounts.

**Comment by MikaalSky** [comment]
@kevinb7 Yeah. It's kinda a funky setup since I'm logged into MikaalSky in Github for Windows, but it commits with Lokio27. Weird.

**Comment by kevinb7** [comment]
@MikaalSky we unfortunately haven't had a chance yet to implement any of the changes that @pamelafox requested after community feedback.  I'll be going on my support rotation in a couple of weeks so I should be able to tackle those changes then.  Can you rename these as variants so that we have both versions?  I like that the colors match better.  I would like to use both happy versions.  For the "hmm" image I like the smaller mouth on the old one, but I like the slant of the mouth on the new one.

**Comment by MikaalSky** [comment]
So, ohnoes-hmm-new and such?

**Comment by kevinbarabash** [comment]
@MikaalSky I'm going close this pull request until the current changes to oh-noes guy have been rolled to all users.  I created https://github.com/Khan/live-editor/issues/454 because I don't want to forget about it.  I would like to process PRs more quickly by either merging or closing as opposed to having the sit in limbo.

**Pull request closed without merging**
