### PR TITLE
Avoid undo avalanche2

### PR DESCRIPTION
**Pull request by ChrisJPhoenix**
OK, I think this is what you want... I hope so. 

Chris

### CODE REVIEW

**Comment by kevinb7** [comment]
I'll have a look Monday.

**Comment by kevinb7** [comment]
@ChrisJPhoenix I checked out your branch and all the tests pass.  I'm a little concerned about all of the unrelated changes in the build files.  I think it's because when the files are being written Windows is using crlf `\r\n` for the end of lines.  I'm going to add a plugin to the gulpfile.js to try to counteract this: https://github.com/takenspc/gulp-convert-newline.  You should also see if your editor supports lf for end of lines.  I'll try to have the plugin in place by end of day.  After that, rebase on master and run `gulp build` and then update the pull request.

**Comment by ChrisJPhoenix** [comment]
I've never used rebase. After reading http://git-scm.com/book/ch3-6.html
I'm guessing I should just do the command "git rebase master" but I also
realize how dangerous guessing is, since I've already pushed commits prior
to doing rebase.

My editor (Webstorm) does support lf, so I'll configure that.

And should I use the '-f' flag on the push to update the pull request? I'm
guessing I have to, since I will have done a rebase... but again, want to
double-check.

Have you read Lev Grossman's Magician series? I'm coming to see using git
as being comparable to his spellcasting process: To do anything creative,
you have to know not only how magic / git works at a detailed level, but
also the physical context of the spell / the workflow of the project, and
people need to study arcana for years (dead languages / the command-line
argument details) to get good at it.

Chris


On Mon, Aug 3, 2015 at 8:58 AM, Kevin Barabash <notifications@github.com>
wrote:

> @ChrisJPhoenix <https://github.com/ChrisJPhoenix> I checked out your
> branch and all the tests pass. I'm a little concerned about all of the
> unrelated changes in the build files. I think it's because when the files
> are being written Windows is using crlf \r\n for the end of lines. I'm
> going to add a plugin to the gulpfile.js to try to counteract this:
> https://github.com/takenspc/gulp-convert-newline. You should also see if
> your editor supports lf for end of lines. I'll try to have the plugin in
> place by end of day. After that, rebase on master and run gulp build and
> then update the pull request.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/pull/372#issuecomment-127287173>.
>



-- 
Chris Phoenix
cphoenix@gmail.com
650-776-5195

**Comment by kevinb7** [comment]
@ChrisJPhoenix try configuring that option and see if that fixes the files.

**Comment by kevinb7** [comment]
To rebase make sure you're in the branch you want to rebase and then do `git rebase master` to rebase the current branch on top of master.  If something messes up you can always do a `git rebase --abort`.

**Comment by ChrisJPhoenix** [comment]
OK....

First, I set Webstorm to treat the project as lf instead of crlf... and it
changed dozens of files. My best guess is that some of the project files
were always crlf and I shouldn't have changed their default.

Then I tried to check in the files and got a bunch of "LF will be replaced
by CRLF" warnings. Google suggests that I should set core.autocrlf to false
to avoid those... because it was true before... which means, shouldn't git
have been taking care of this all along?

Then I did "git rebase master" in my avoid_undo_avalanche branch and all it
said was "Current branch avoid_undo_avalanche is up to date." So I think I
must have missed or misunderstood some instruction.

Before all this, I tried to do a "git pull" to get the gulpfile plugin you
were planning to add, and it said everything is up to date. So I guess I
don't know how to pull the latest changes. What other incantations do I
need?

Sorry to be taking so much calendar and clock time to finish this up. It's
my first open-source project using an unfamiliar git workflow. And to be
honest, working with git is not at all fun for me.

How did you get good at git? The paragraph of instructions you sent me a
few iterations ago would have taken me at least a day to generate and test.
Is there, somewhere out there, a tutorial or reference that will get me to
that level in fewer than 500 pages? (I've been using git for two years,
I've read at least 100 pages in ten different tutorials, plus some man
pages, and I'm starting to learn which concepts are missing from all the
tutorials - things like .gitignore.)

Chris



On Mon, Aug 3, 2015 at 6:43 PM, Kevin Barabash <notifications@github.com>
wrote:

> To rebase make sure you're in the branch you want to rebase and then do git
> rebase master to rebase the current branch on top of master. If something
> messes up you can always do a git rebase --abort.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/pull/372#issuecomment-127452139>.
>



-- 
Chris Phoenix
cphoenix@gmail.com
650-776-5195

**Comment by kevinb7** [comment]
So ended up not adding a gulpfile plugin and instead went the .editorconfig route.  See http://editorconfig.org/ for details.

Yeah that's weird that the tutorials don't cover .gitignore.  I watched a few gitcast videos: https://www.youtube.com/playlist?list=PLttwD7NyH3omQLyVtan0CFOX_UWItX_yG which are okay.  Then I started contributing to projects, mainly this one and [KaTeX](https://github.com/khan/katex).  For KaTeX the maintainers wanted all pull requests squashed so I learned how to do that.  I've also had received some helpful advice from co-workers such as:
- using `git bisect` to quickly find where a bug was introduced
- using `git reflog` to fix issues that you thought were permanent, e.g. rewriting history with rebase can actually be undone
- using `git branch --set-upstream-to <branch>` to control which branch the current branch is following, i.e. pulls from when you do a `git pull`
- using `git branch -vv` to see all of the branch you have locally and which branch they're following.

I think the issue your experience with `git pull` is that you're pull from `origin/avoid_undo_avalanche2` which doesn't have the .editorconfig changes.  Those are on master.  To get those you'd need to `git checkout master` followed by `git fetch` and then `git merge upstream/master`.  The last command assumes that you've set up a remote called `upstream`.  You can check by using `git remote -v`.

In terms of getting git to correct the line endings it seems like the preferred way to do it is to have a .gitattributes file in the repo so that people don't have to change the settings manually.  See http://stackoverflow.com/questions/2517190/how-do-i-force-git-to-use-lf-instead-of-crlf-under-windows.  I can add one and then you can do the rebase.  I'd squash my commits before the rebase.  If you get merge conflicts in the build files just rebuild them.

**Comment by kevinb7** [comment]
@ChrisJPhoenix you can try the .gitattributes solution without having to rebase by creating a .gitattributes file containing these lines:
```
/js/*.js text eol=lf
/build/*.js text eol=lf
```
I'm not sure if this will work.  You may have to delete `build/js/` and rebuild the files.  Let me know how that goes.  Please post console logs if anything goes awry.

**Comment by kevinb7** [comment]
I added the gulp plugin to fix the line endings on the build files.  It picked up a few `\r\n` on some of the files.  See https://github.com/Khan/live-editor/commit/7a7dd564f5e28a72db61b738fb64ed0e110e4959.

**Comment by ChrisJPhoenix** [comment]
OK, I'd really like to get this finished up by Wednesday - I'm making time
on weekdays.

Right now I'm on branch avoid_undo_avalanche2 and I have a bunch of
"Modified: external/TraceKit" etc, and I don't know whether to commit them
or revert them - or, in fact, how to commit them. I've learned I need to
have a clean status before I switch branches - otherwise things get ugly
fast.

When I try "git add ." as the "git status" suggests, it doesn't add those
directories. I guess they're in sub-repositories but I've never learned
subrepositories, and I really don't have time to learn them this week.

If we could schedule a 15 minute chat, it would save me several hours, and
we could finally be done with this thing.

Chris


On Thu, Aug 13, 2015 at 10:49 PM, Kevin Barabash <notifications@github.com>
wrote:

> I added the gulp plugin to fix the line endings on the build files. It
> picked up a few \r\n on some of the files. See 7a7dd56
> <https://github.com/Khan/live-editor/commit/7a7dd564f5e28a72db61b738fb64ed0e110e4959>.
>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/pull/372#issuecomment-130980687>.
>



-- 
Chris Phoenix
cphoenix@gmail.com
650-776-5195

**Comment by kevinb7** [comment]
> If we could schedule a 15 minute chat, it would save me several hours, and
we could finally be done with this thing.

You bet.  I set up a gitter room for this repo so that we can chat.  I'll be hanging out in the room all day except from 11:30 to 1:30 MST.  I also have a meeting in the afternoon during which I won't be able to chat much.

I checked out your branch and I'm going to see if I can try to get rid of some of these issues.  I'll post the commands I use.  I'm sorry that this is dragging out so long.  Your code looks good and so do the tests so it's unfortunate that the tools are getting in the way.

**Comment by kevinb7** [comment]
First I need to get a copy of your branch.  (You don't have to do this because you already have your branch)
-  `git remote add ChrisJPhoenix https://github.com/ChrisJPhoenix/live-editor` (adds a remote, in addition to 'origin' called ChrisJPhoenix that points to your fork)
- `git checkout ChrisJPhoenix/avoid_undo_avalanche2` (checks out your branch, currently HEAD is detached)
- `git checkout -b avoid_undo_avalanche2` (creates a local branch pointing to the most recent commit in your branch)

Next I want to make sure that there's only a single commit before rebasing on to master.  If there are merge conflicts then this makes it easier to deal with them I find because you deal with them all at once.  Looking at the last two commits I see that you were just trying to deal with whitespace issues so we can just get rid of them.
- `git reset --hard HEAD~2` (This removes the last two commits from the current branch.  Since this is done locally, if you mess something up you can always do a fresh checkout from github.  I've done this many times in the past.  In this case you could also just checkout the remote branch again which is a lot quicker)

Before I actually rebase `avoid_undo_avalanche2` onto `master`, I'm going to check that `master` is up to date by doing:
- `git checkout master`
- `git pull`

Now I'm going switch back to `avoid_undo_avalanche2` and rebase.  At any point in time if you want to check which branch you're on (and what other branches are available) you can do `git branch -vv`.
- `git checkout avoid_undo_avalanche2`
- `git rebase master`

I have a couple of merge conflicts.  Before continuing I want to see the current lay of the land so I run `git status` which gives me this:
```
rebase in progress; onto 687aa60
You are currently rebasing branch 'avoid_undo_avalanche' on '687aa60'.
  (fix conflicts and then run "git rebase --continue")
  (use "git rebase --skip" to skip this patch)
  (use "git rebase --abort" to check out the original branch)

Changes to be committed:
  (use "git reset HEAD <file>..." to unstage)

        modified:   js/ui/tooltip-engine.js
        modified:   js/ui/tooltips/color-picker.js
        modified:   js/ui/tooltips/number-scrubber.js
        modified:   tests/tooltips/index.html
        modified:   tests/tooltips/shared.js

Unmerged paths:
  (use "git reset HEAD <file>..." to unstage)
  (use "git add <file>..." to mark resolution)

        both modified:   external/colorpicker/colorpicker.js
        both modified:   tests/tooltips/tooltips_test.js

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   external/processing-js (new commits)
```
See that processing-js has been updated so I need to update that submodule with `git submodule update`.  I also check which commit it wanted to update processing-js to by using SourceTree which is a pretty handy GUI for cases like this where I want to see want the proposed changes are.

Now I'm left with the merge conflicts to resolve.  I open up colorpicker.js in my editor.  Since I have invisible characters turned on it's easy to see that half of the file is the original tabbed version and the half has spaces.  I delete the lines with tabs and remove the merge conflict markers.  Afterwards I'm only left with two lines that are different and they're just missing trailing whitespace so I mark this file as resolved by doing `git add external/colorpicker/colorpicker.js`.  Looking at tooltips_test.js, there's a very small merge conflict where one line has a trailing space.  I grab the line without the trailing space and mark this file resolved as well using `git add tests/tooltips/tooltips_test.js`.

Once all of the conflicts are resolved I finish the rebase with `git rebase --continue`.  Next I'll run all of the tests and make any additional fixes.

**Comment by kevinb7** [comment]
After the rebase I had a look at the history with `git log` and noticed that there are now 5 of your commits in the `avoid_undo_avalanche2` branch sitting on top of HEAD of `master`.  Running `gulp` doesn't yield any changes.  Running the tests in http://localhost:63342/live-editor/tests/output/pjs/index.html yields two failures right at the end.  These failures are my fault not your fault and I have fixed them on another branch.  Having the gitter will make it much easier to answer questions about stuff like this.  This looks good to merge now.  We chat tomorrow about how you want to proceed.

**Comment by kevinb7** [comment]
I was running `gulp build` in the wrong folder.  After running it in the correct folder only build file that was modified was `build/js/live-editor.tooltips.js` which seems about right.  I ran the tests again and they all pass except for the last one which I already mentioned.  Now this is good to go for sure.

**Comment by ChrisJPhoenix** [comment]
OK... I went to the gitter room and it seems you're not there. If you're on
Mountain time, then it's 6:30 PM already so I'm guessing "all day" meant
Tuesday?

It took me 15 minutes of googling to find the gitter badge - it's not text
searchable! In hindsight, the "Added Gitter badge" to README.md could have
told me where to look, but I had to read Wikipedia to find out that I was
supposed to be looking for a "gitter badge" rather than e.g. logging in
through gitter or finding the right subpart of the Github UI.

It looks like this email is all a description of stuff you've done, not
stuff I need to do?

I'm thinking a good comparison for git is the US tax code. It is not enough
to be smart; you have to know all the details. The 80/20 rule does not
apply. A friend of mine believe-it-or-not told me today that the tax code
"plainly states" that an employee deferring their salary is a taxable
event. Sure it's plain - if you know every detail. Likewise for knowing the
difference between
  Unmerged paths: both modified: external/...
and
  Changes not staged for commit: modified: external/...
much less what to do about each one.

I suppose after I've made a few contributions this will all be second
nature and I'll wonder why it seemed so hard. I appreciate that you have
never been impatient or condescending with me.

Chris


On Mon, Aug 17, 2015 at 5:22 PM, Kevin Barabash <notifications@github.com>
wrote:

> First I need to get a copy of your branch. (You don't have to do this
> because you already have your branch)
>
>    - git remote add ChrisJPhoenix
>    https://github.com/ChrisJPhoenix/live-editor (adds a remote, in
>    addition to 'origin' called ChrisJPhoenix that points to your fork)
>    - git checkout ChrisJPhoenix/avoid_undo_avalanche2 (checks out your
>    branch, currently HEAD is detached)
>    - git checkout -b avoid_undo_avalanche2 (creates a local branch
>    pointing to the most recent commit in your branch)
>
> Next I want to make sure that there's only a single commit before rebasing
> on to master. If there are merge conflicts then this makes it easier to
> deal with them I find because you deal with them all at once. Looking at
> the last two commits I see that you were just trying to deal with
> whitespace issues so we can just get rid of them.
>
>    - git reset --hard HEAD~2 (This removes the last two commits from the
>    current branch. Since this is done locally, if you mess something up you
>    can always do a fresh checkout from github. I've done this many times in
>    the past. In this case you could also just checkout the remote branch again
>    which is a lot quicker)
>
> Before I actually rebase avoid_undo_avalanche2 onto master, I'm going to
> check that master is up to date by doing:
>
>    - git checkout master
>    - git pull
>
> Now I'm going switch back to avoid_undo_avalanche2 and rebase. At any
> point in time if you want to check which branch you're on (and what other
> branches are available) you can do git branch -vv.
>
>    - git checkout avoid_undo_avalanche2
>    - git rebase master
>
> I have a couple of merge conflicts. Before continuing I want to see the
> current lay of the land so I run git status which gives me this:
>
> rebase in progress; onto 687aa60
> You are currently rebasing branch 'avoid_undo_avalanche' on '687aa60'.
>   (fix conflicts and then run "git rebase --continue")
>   (use "git rebase --skip" to skip this patch)
>   (use "git rebase --abort" to check out the original branch)
>
> Changes to be committed:
>   (use "git reset HEAD <file>..." to unstage)
>
>         modified:   js/ui/tooltip-engine.js
>         modified:   js/ui/tooltips/color-picker.js
>         modified:   js/ui/tooltips/number-scrubber.js
>         modified:   tests/tooltips/index.html
>         modified:   tests/tooltips/shared.js
>
> Unmerged paths:
>   (use "git reset HEAD <file>..." to unstage)
>   (use "git add <file>..." to mark resolution)
>
>         both modified:   external/colorpicker/colorpicker.js
>         both modified:   tests/tooltips/tooltips_test.js
>
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
>
>         modified:   external/processing-js (new commits)
>
> See that processing-js has been updated so I need to update that submodule
> with git submodule update. I also check which commit it wanted to update
> processing-js to by using SourceTree which is a pretty handy GUI for cases
> like this where I want to see want the proposed changes are.
>
> Now I'm left with the merge conflicts to resolve. I open up colorpicker.js
> in my editor. Since I have invisible characters turned on it's easy to see
> that half of the file is the original tabbed version and the half has
> spaces. I delete the lines with tabs and remove the merge conflict markers.
> Afterwards I'm only left with two lines that are different and they're just
> missing trailing whitespace so I mark this file as resolved by doing git
> add external/colorpicker/colorpicker.js. Looking at tooltips_test.js,
> there's a very small merge conflict where one line has a trailing space. I
> grab the line without the trailing space and mark this file resolved as
> well using git add tests/tooltips/tooltips_test.js.
>
> Once all of the conflicts are resolved I finish the rebase with git
> rebase --continue. Next I'll run all of the tests and make any additional
> fixes.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/pull/372#issuecomment-132003324>.
>



-- 
Chris Phoenix
cphoenix@gmail.com
650-776-5195

**Comment by kevinb7** [comment]
> OK... I went to the gitter room and it seems you're not there. If you're on
Mountain time, then it's 6:30 PM already so I'm guessing "all day" meant
Tuesday?

Sorry, I should've been more specific.  Yes, Tuesday.

> It took me 15 minutes of googling to find the gitter badge - it's not text
searchable!

I should've posted a direct link.

> It looks like this email is all a description of stuff you've done, not stuff I need to do?

It's all done.  I have it on a local branch.  I wanted to chat with you first before merging it in.  It includes your commits so you'll get credit for the commits on github.

> knowing the difference between
  Unmerged paths: both modified: external/...
and
  Changes not staged for commit: modified: external/...
much less what to do about each one.

Yeah, using git with submodules can be a challenge.  Using a tool like SourceTree can be helpful because it has a window that shows what's been staged and what isn't and it's super easy to move files and parts of files between the two states.  I highly recommend SourceTree although I remember it being a bit of pain to set up on Windows.  If that's still the case there are other git GUIs that might be worth checking out.  I started out using the GUI for pretty much everything and over time as I've learned more git-fu on the command line I don't use the GUI as much.

**Comment by ChrisJPhoenix** [comment]
Eh. If I'd known what a "badge" was I would've found it more quickly. (I
thought the Singularity was supposed to be fun and interesting, not just
make us feel like fogies! :-)

Super easy to move parts of files between states? Sounds good - I have an
Ubuntu running on my Windows, so maybe I'll try it there.

You may be amused by
http://typicalprogrammer.com/linus-torvalds-goes-off-on-linux-and-git/

I'll chat with you tomorrow morning.

Chris


On Mon, Aug 17, 2015 at 5:59 PM, Kevin Barabash <notifications@github.com>
wrote:

> OK... I went to the gitter room and it seems you're not there. If you're on
> Mountain time, then it's 6:30 PM already so I'm guessing "all day" meant
> Tuesday?
>
> Sorry, I should've been more specific. Yes, Tuesday.
>
> It took me 15 minutes of googling to find the gitter badge - it's not text
> searchable!
>
> I should've posted a direct link.
>
> It looks like this email is all a description of stuff you've done, not
> stuff I need to do?
>
> It's all done. I have it on a local branch. I wanted to chat with you
> first before merging it in. It includes your commits so you'll get credit
> for the commits on github.
>
> knowing the difference between
> Unmerged paths: both modified: external/...
> and
> Changes not staged for commit: modified: external/...
> much less what to do about each one.
>
> Yeah, using git with submodules can be a challenge. Using a tool like
> SourceTree can be helpful because it has a window that shows what's been
> staged and what isn't and it's super easy to move files and parts of files
> between the two states. I highly recommend SourceTree although I remember
> it being a bit of pain to set up on Windows. If that's still the case there
> are other git GUIs that might be worth checking out. I started out using
> the GUI for pretty much everything and over time as I've learned more
> git-fu on the command line I don't use the GUI as much.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/Khan/live-editor/pull/372#issuecomment-132010054>.
>



-- 
Chris Phoenix
cphoenix@gmail.com
650-776-5195

**Comment by kevinb7** [comment]
I'm closing this because these changes have been merged in https://github.com/Khan/live-editor/commit/49b40b9185ec458b58fb1bd48f3cf927e4458f24.

**Comment by kevinb7** [comment]
@ChrisJPhoenix github isn't associating your email address from the commit with your github account.  If you want github credit you'll have to add the email address listed on the commit to your github account.
screen shot 2015-08-18 at 4 28 29 pm

**Pull request closed without merging**
