### PR TITLE
use ExtendedOutputImages for the pjs image picker

### PR DESCRIPTION
**Pull request by JetStarBlues**
Addresses #641

### CODE REVIEW

**Comment by JetStarBlues** [comment]
`npm test` passed all tests locally. It looks like the failure at Travis CI is due to the version of npm it is using. I used:

- npm 5.2.0
- bower 1.8.0
- gulp 3.9.1

**Comment by codeHusky** [comment]
Check the README.

**Comment by JetStarBlues** [comment]
Ah seen. Somehow I missed the preamble and scrolled straight to the build instructions.

**Comment by pamelafox** [comment]
I'm going to close this PR, as the photos weren't intended for use in ProcessingJS, they're not particularly well-sized for that use case.

**Pull request closed without merging**
